  version: 0.2

  phases:
    pre_build:
      commands:
       - echo logging to AMAZON ECR `date`
       - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
       - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
       - IMAGE_TAG=${COMMIT_HASH:-latest}
    build:
      commands:
        - echo docker build images `date`
        - docker build -t $REPOSITORY_URI:$IMAGE_ID .
        - echo "Tagging ECR images"
        - docker tag $REPOSITORY_URI:$IMAGE_ID $REPOSITORY_URI:$IMAGE_TAG
    post_build:
     commands:
      - echo docker image push to ECR `date`
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$IMAGE_ID
      - echo writing ecs task definationfile
      - printf '[{"name":"container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json  # ECS needs this!

artifacts:
  files:
    - imagedefinitions.json
